-- Create products table
CREATE TABLE products (
  barcode TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create prices table
CREATE TABLE prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barcode TEXT REFERENCES products(barcode) ON DELETE CASCADE,
  store TEXT NOT NULL,
  price NUMERIC NOT NULL,
  date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- (Optional) Enable Row Level Security (RLS)
-- If you want to allow anonymous access for this demo:
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE prices ENABLE ROW LEVEL SECURITY;

-- Allow public read/write access (Not recommended for production, but good for testing)
CREATE POLICY "Allow public access for products" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access for prices" ON prices FOR ALL USING (true) WITH CHECK (true);
